/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assgn.kaizhi;

import assgn.ArrList;
import assgn.ArrayListInterface;
import assgn.Customer;
import assgn.DeliveryMen;
import assgn.Delivery;
import assgn.Menu;
import assgn.Order;
import assgn.Turn;
import assgn.TurnInterface;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KaiZhi
 */
public class DeliveryMenCheckAddress extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryMenScreen
     */
    ArrayListInterface<Customer> customer = new ArrList<>();
    ArrayListInterface<Menu> menu = new ArrList<>();
    ArrayListInterface<Order> order = new ArrList<>();
    ArrayListInterface<Order> order1 = new ArrList<>();
    ArrayListInterface<assgn.Delivery> delivery = new ArrList<>();
    assgn.DeliveryInterface deli = new assgn.Delivery();
    DefaultTableModel model;
    DeliveryMen staff;
    ClockInClockOut cico;

    public DeliveryMenCheckAddress() {
        initComponents();
    }

    public DeliveryMenCheckAddress(DeliveryMen thatguy, ClockInClockOut cico) {

        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        this.staff = thatguy;
        this.cico = cico;
        jlblThatguy.setText("Name : " + thatguy.getName());

        Customer c = new Customer("Name", "HOO LAND", "012378999", "email", "hello");
        Customer c1 = new Customer("Name1", "no MAN LAND", "014378999", "email1", "hello1");

        customer.add(c);
        customer.add(c1);

        Menu m = new Menu("1", "Burger", 12.3);
        Menu m1 = new Menu("2", "hotdog", 10.5);
        Menu m2 = new Menu("3", "fries", 5.0);

        menu.add(m);
        menu.add(m1);
        menu.add(m2);

        Order o = new Order(m);
        Order o1 = new Order(m1);

        order.add(o);
        order.add(o1);

        Delivery d = new assgn.Delivery("1", c, "Not deliver", order, this.staff);

        delivery.add(d);
        //1 delivery

        Order o2 = new Order(m2);
        Order o3 = new Order(m);

        order1.add(o3);
        order1.add(o2);

        Delivery de1 = new assgn.Delivery("2", c1, "Not deliver", order1, this.staff);

        delivery.add(de1);

        Object row[] = new Object[3];
        for (int i = 0; i < delivery.size(); i++) {
            if (thatguy == delivery.get(i).getDeliveryMen()) {
                row[0] = delivery.get(i).getDeliveryID();
                row[1] = delivery.get(i).getCustomer().getName();
                row[2] = delivery.get(i).getCustomer().getAddress();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtfDeliveryID = new javax.swing.JTextField();
        jbtSearchAddress = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jlblThatguy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery ID", "Customer Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jtfDeliveryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDeliveryIDActionPerformed(evt);
            }
        });

        jbtSearchAddress.setText("Search ID");
        jbtSearchAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchAddressActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Delivery ID:");

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jlblThatguy.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jbtSearchAddress))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfDeliveryID, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblThatguy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnBack)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack)
                    .addComponent(jlblThatguy))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDeliveryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSearchAddress)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDeliveryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDeliveryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDeliveryIDActionPerformed

    private void jbtSearchAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchAddressActionPerformed
        // TODO add your handling code here:

        if (deli.checkDeliveryID(delivery, jtfDeliveryID.getText())) {
            JOptionPane.showMessageDialog(null, delivery.get(deli.getIndex()).getCustomer().getAddress());
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Delivery Id", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtSearchAddressActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:

        DeliveryMenMenuScreen next = new DeliveryMenMenuScreen(staff, cico);
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Confirm to go to main menu?");
        panel.add(label);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "The title",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        if (option == 0) {
            this.setVisible(false);
            next.setVisible(true);
        }
    }//GEN-LAST:event_jbtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryMenCheckAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryMenCheckAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryMenCheckAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryMenCheckAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryMenCheckAddress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtSearchAddress;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JLabel jlblThatguy;
    private javax.swing.JTextField jtfDeliveryID;
    // End of variables declaration//GEN-END:variables
}
