/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assgn;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mixed_97
 */
public class Cart extends javax.swing.JFrame {

    ArrayListInterface<DeliveryMen> deliveryMen = new ArrList<>();
    ArrayListInterface<Order> order = new ArrList<>();
    Customer customer;
    int index;
    public Cart(){
    initComponents();
    }
    
    public Cart(ArrayListInterface<Order> order) {
        this.order = order;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Cart");
        displayOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        confrimOrder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        _menuid = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        _quantity = new javax.swing.JTextField();
        ChangeQuan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CancelOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Cart");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu ID", "Name", "Price", "Quantity", "Sub-Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        confrimOrder.setText("Confrim Order");
        confrimOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimOrderActionPerformed(evt);
            }
        });

        jLabel2.setText("Menu Id :");

        x.setText("Quantity :");

        ChangeQuan.setText("Change Quantity");
        ChangeQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeQuanActionPerformed(evt);
            }
        });

        jButton1.setText("Remove order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CancelOrder.setText("Cancel");
        CancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(x))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_menuid, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ChangeQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CancelOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confrimOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(_menuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x)
                            .addComponent(_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(ChangeQuan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confrimOrder)
                    .addComponent(CancelOrder))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeQuanActionPerformed
        if(_menuid.getText().isEmpty() || _quantity.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Please don't left the quantity or menu id Empty", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            
            int quantity = Integer.parseInt(_quantity.getText());
            if(checkOrder() && quantity > 0){
                order.get(index).setQuantity(quantity);
                order.get(index).setTotal();
                JOptionPane.showMessageDialog(null, "Successfully change the quantity");
                removeDisplay();
                displayOrder();
            }
            else if(!checkOrder()){
                JOptionPane.showMessageDialog(null, "No such order in the list", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_ChangeQuanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Remove Order
        if(!_menuid.getText().isEmpty()){
        if(checkOrder()){
            order.remove(order.get(index));
            removeDisplay();
            displayOrder();
            JOptionPane.showMessageDialog(null, "Successfully remove order from cart");
        }
        else{
             JOptionPane.showMessageDialog(null, "No such order in the list", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
             JOptionPane.showMessageDialog(null, "Don't left the menu id Empty", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confrimOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimOrderActionPerformed
        // Confirm Order
        // all thing become delivery
        //later do but not now
        
        
    }//GEN-LAST:event_confrimOrderActionPerformed

    private void CancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }
    
    public void setDeliveryMen(ArrayListInterface<DeliveryMen> deliveryMen){
        this.deliveryMen=deliveryMen;
    }
    public void setCustomer(Customer customer){
        this.customer=customer;
    }
    public void setOrder(ArrayListInterface<Order> order){
        this.order = order;
    }
    
    public boolean checkOrder(){
        
        for(int i =0;i<order.size();i++){
            if(order.get(i).getMenuID().equals(_menuid.getText()))
            {
                index = i;
                return true;
            }
        }
        
        return false;
    }
    
    public void removeDisplay(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }
    
    public void displayOrder(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        Object [] row = new Object[5];
        for(int i =0; i < order.size();i++){
            row[0] = order.get(i).getMenuID();
            row[1]= order.get(i).getMenuName();
            row[2] = String.format("%.2f", order.get(i).getPrice());
            row[3] = order.get(i).getQuantity();
            row[4] = String.format("%.2f", order.get(i).getTotal());
            model.addRow(row);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelOrder;
    private javax.swing.JButton ChangeQuan;
    private javax.swing.JTextField _menuid;
    private javax.swing.JTextField _quantity;
    private javax.swing.JButton confrimOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
