/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assgn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mixed_97
 */
public class DeliveryTable extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryTable
     * do u know y helium ,curium and barium is known as medical element because if u cant helium or curium then u just gonna barium.
     */
    ArrayListInterface<DeliveryMen> deliveryMen = new ArrList<>();
    ArrayListInterface<Customer> customer = new ArrList<>();
    ArrayListInterface<Menu> menu = new ArrList<>();
    ArrayListInterface<Order> order = new ArrList<>();
    ArrayListInterface<Order> order1 = new ArrList<>();
    ArrayListInterface<Delivery> delivery = new ArrList<>();
    DeliveryInterface deli = new Delivery();    
    DefaultTableModel model;
    
    public DeliveryTable() {
        initComponents();
        model = (DefaultTableModel)jTable1.getModel();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        TurnInterface t = new Turn();
        
        DeliveryMen d1 = new DeliveryMen("Nicholas","666","192","Somewhere","01234567",123.00);
        DeliveryMen d2 = new DeliveryMen("Soon Jian Kai","456","999","No where","01899997",223.00);
        DeliveryMen d3 = new DeliveryMen("Ng Poh Hooi","555","456","LoL","01934567",323.00);
        DeliveryMen d4 = new DeliveryMen("Ong Kai Zhi","777","789","Wonder Land","01134567",423.00);
        
        deliveryMen.add(d1);
        deliveryMen.add(d2);
        deliveryMen.add(d3);
        deliveryMen.add(d4);
        
        Customer c = new Customer("Name", "HOO LAND", "012378999","email","hello");
        Customer c1 = new Customer("Name1", "no MAN LAND", "014378999","email1","hello1");
        
        customer.add(c);
        customer.add(c1);
        
        Menu m = new Menu("1","Burger",12.3);
        Menu m1 = new Menu("2", "hotdog",10.5);
        Menu m2 = new Menu("3","fries",5.0);
        
        menu.add(m);
        menu.add(m1);
        menu.add(m2);
        
        Order o = new Order(m);
        Order o1 = new Order(m1);
        
        order.add(o);
        order.add(o1);
        
        Delivery d = new Delivery("1", c, "Not deliver", order, deliveryMen.get(t.findTurn(deliveryMen)- 1) );
        
        delivery.add(d);
        //1 delivery
        
        
        Order o2 = new Order(m2);
        Order o3 = new Order(m);
        
        order1.add(o3);
        order1.add(o2);
        
        Delivery de1 = new Delivery("2", c1, "Not deliver", order1, deliveryMen.get(t.findTurn(deliveryMen)- 1));
        
        
        
        delivery.add(de1);
        //2nd delivery
        
        Delivery de2 = new Delivery("3",c1, "Not deliver", order1, deliveryMen.get(t.findTurn(deliveryMen)-1));
        delivery.add(de2);
        
        Delivery de3 = new Delivery("4",c1, "Not deliver", order1, deliveryMen.get(t.findTurn(deliveryMen)-1));
        delivery.add(de3);
        
        Delivery de4 = new Delivery("5",c1, "Not deliver", order1, deliveryMen.get(t.findTurn(deliveryMen)-1));
        delivery.add(de4);
        
        Delivery de5 = new Delivery("6",c1, "Not deliver", order1, deliveryMen.get(t.findTurn(deliveryMen)-1));
        delivery.add(de5);
        
         
        deli.displayTable(model, delivery);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        _deliveryid = new javax.swing.JTextField();
        _ConfirmDelivery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Delivery ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", " address", "Contact No", "Delivery Id", "Status", "DeliveryMen id", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Delivery ID :");

        _ConfirmDelivery.setText("Confirm Delivery");
        _ConfirmDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ConfirmDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_ConfirmDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_deliveryid, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(_deliveryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(_ConfirmDelivery)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _ConfirmDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ConfirmDeliveryActionPerformed
        // TODO add your handling code here:
        if(deli.checkDeliveryID(delivery, _deliveryid.getText())){
            delivery.get(deli.getIndex()).setStatus("Delivered");
            deli.removeDisplay(model);
            deli.displayTable(model, delivery);
            JOptionPane.showMessageDialog(null, "Successfully deliver order "+ delivery.get(deli.getIndex()).deliveryID);
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Delivery Id", "Error", JOptionPane.ERROR_MESSAGE );
        }
        
    }//GEN-LAST:event__ConfirmDeliveryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryTable().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _ConfirmDelivery;
    private javax.swing.JTextField _deliveryid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
